### PR TITLE
:memo: update README

### PR DESCRIPTION
**Pull request by javedali-dev**
fix typo in README

### CODE REVIEW

**Comment by jbelien** [comment]
Thanks @javedali-dev 👍 
We're using Gitbook as source, I've made the update there.

**Comment by mietcls** [comment]
This was a qwerty dev joke, not a typo. But you have passed the test @javedali-dev. Please put it back.

**Comment by jbelien** [comment]
Sorry @mietcls ! I'll revert it.

**Comment by mietcls** [comment]
Ah no worries, apparently nobody makes this joke anymore and it just looks wrong. Let's keep it ;-)

**Pull request closed without merging**
